import {
  SearchRequest,
  SearchResponse,
  SearchDetailResponse,
  MaterialDetailResponse,
  CompareRequest,
  CompareResponse,
  ReportResponse,
  ApiStatusResponse,
  HealthResponse,
  HTTPValidationError,
} from "@/types";

export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ||
  "https://mat-search-ai-backend.vercel.app";

export class ApiError extends Error {
  public readonly status: number;
  public readonly statusText?: string;
  public readonly details?: unknown;

  constructor(
    message: string,
    status: number,
    statusText?: string,
    details?: unknown
  ) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.statusText = statusText;
    this.details = details;
  }
}

async function request<T>(path: string, options: RequestInit = {}): Promise<T> {
  const url = `${API_BASE_URL.replace(/\/$/, "")}${path}`;

  let response: Response;
  try {
    response = await fetch(url, {
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...(options.headers || {}),
      },
    });
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Unknown network error";
    throw new ApiError(
      `Network Error: Failed to communicate with MatSearch AI backend at ${API_BASE_URL}. ${message}`,
      0,
      "NETWORK_FAILURE"
    );
  }

  if (!response.ok) {
    let errorBody: unknown;
    try {
      errorBody = await response.json();
    } catch {
      try {
        errorBody = await response.text();
      } catch {
        errorBody = null;
      }
    }

    let errorMessage = `Request failed with status ${response.status}`;

    switch (response.status) {
      case 400:
        errorMessage = "Bad Request: The search request is invalid.";
        break;
      case 404:
        errorMessage = "Not Found: The requested resource could not be found on the backend.";
        break;
      case 409:
        errorMessage = "Conflict: The resource is in a conflicting state.";
        break;
      case 422: {
        const valError = errorBody as HTTPValidationError | null;
        if (valError && Array.isArray(valError.detail) && valError.detail.length > 0) {
          const formatted = valError.detail
            .map((d) => `${d.loc.join(".")}: ${d.msg}`)
            .join("; ");
          errorMessage = `Validation Error (422): ${formatted}`;
        } else {
          errorMessage = "Validation Error (422): The submitted data failed backend schema validation.";
        }
        break;
      }
      case 429:
        errorMessage = "Rate Limit Exceeded (429): Too many requests. Please wait before making more requests.";
        break;
      default:
        if (response.status >= 500) {
          errorMessage = `Server Error (${response.status}): MatSearch AI backend is temporarily unavailable or encountered an error.`;
        }
        break;
    }

    throw new ApiError(errorMessage, response.status, response.statusText, errorBody);
  }

  return response.json() as Promise<T>;
}

/**
 * POST /api/search/
 * Create a new autonomous materials discovery search.
 */
export async function createSearch(payload: SearchRequest): Promise<SearchResponse> {
  return request<SearchResponse>("/api/search/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * GET /api/search/{search_id}
 * Retrieve the latest persisted workflow state for a search.
 */
export async function fetchSearch(id: string): Promise<SearchDetailResponse> {
  return request<SearchDetailResponse>(`/api/search/${encodeURIComponent(id)}`, {
    method: "GET",
  });
}

/**
 * GET /api/material/{material_id}
 * Retrieve one real material record from Materials Project.
 */
export async function fetchMaterial(materialId: string): Promise<MaterialDetailResponse> {
  return request<MaterialDetailResponse>(`/api/material/${encodeURIComponent(materialId)}`, {
    method: "GET",
  });
}

/**
 * POST /api/compare/
 * Compare multiple real Materials Project materials.
 */
export async function compareMaterials(payload: CompareRequest): Promise<CompareResponse> {
  return request<CompareResponse>("/api/compare/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * GET /api/reports/{search_id}
 * Retrieve the report generated by the Report Agent for a search.
 */
export async function fetchReport(searchId: string): Promise<ReportResponse> {
  return request<ReportResponse>(`/api/reports/${encodeURIComponent(searchId)}`, {
    method: "GET",
  });
}

/**
 * POST /api/reports/{search_id}/generate
 * Regenerate or return the existing workflow report.
 */
export async function generateReport(searchId: string): Promise<ReportResponse> {
  return request<ReportResponse>(`/api/reports/${encodeURIComponent(searchId)}/generate`, {
    method: "POST",
  });
}

/**
 * GET /api/status
 * Get the backend operational status.
 */
export async function fetchApiStatus(): Promise<ApiStatusResponse> {
  return request<ApiStatusResponse>("/api/status", {
    method: "GET",
  });
}

/**
 * GET /health
 * Check backend health.
 */
export async function fetchHealth(): Promise<HealthResponse> {
  return request<HealthResponse>("/health", {
    method: "GET",
  });
}
